### ISSUE TITLE
Duration less than 1s

### ISSUE THREAD

**Issue by Norithiel** [horshack-dpreview/Photoshop-Timeline-Layer-Resizer#1]
Hi! Thank you so much for making plugin like this! I'm just curious how I can set frame duration for less than 1 second? I tried decimals with dot and coma, but it didn't work. Thanks!

**Comment by horshack-dpreview** [comment]
You can set sub-second durations by specifying a 0 (zero) for the "Seconds" field and the number of frames you want in the "Frames" field.
